export CC="${CC_base}"
export CXX="${CXX_base}"
export CMAKE_PREFIX_PATH="${CMAKE_PREFIX_PATH_base}"
export CMAKE_LIBRARY_PATH="${CMAKE_LIBRARY_PATH_base}"
export CPATH="${CPATH_base}"
export LIBRARY_PATH="${LIBRARY_PATH_base}"
